name: Sync main to fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to fork
        run: |
          git config user.name "Cohii"
          git config user.email "hengjunxiangg@gmail.com"
          
          git remote add fork https://x-access-token:${{ secrets.SYNC_FORK_TOKEN }}@github.com/Cohii2/expenses_app.git
          
          git push fork main --force
